services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/td7:/opt/airflow/td7
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB


volumes:
  postgres-db-volume:

   